name: Create Release

on:
    release:
        types:
            - published

jobs:
    build-release:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            -   name: Increment Build.gradle version
                run: |
                    version=$(git describe --tags --abbrev=0 | sed 's/v//g')
                    new_version=$(echo $version | awk -F. '{print $1"."$2"."$3}')
                    echo $tag_version
                    if [ "$new_version" == "$tag_version" ]; then
                      echo "Version already up to date"
                    else
                      echo "Version up to date"
                      echo $new_version
                      sed -i "s/version = '[^']*'/version = '$new_version'/g" build.gradle.kts
                      git add .
                    fi
            -   name: Commit & Push changes
                uses: actions-js/push@master
                with:
                    github_token: ${{ secrets.TOKEN }}
                    message: "Release version ${{ github.ref }} [skip ci]"
                    force-add: "true"
