name: Release Drafter

on:
    pull_request:
        types: [ closed ] #1. PR이 closed되면 작동

jobs:
    desktop-draft-release:
        runs-on: ubuntu-18.04
        # 2. PR이 main에 merge되고, 라벨에 desktop이 포함된 경우 실행
        if: github.event.pull_request.merged == true && github.base_ref == 'main' && contains(github.event.pull_request.labels.*.name, 'documentation')
        steps:
            -   name: Release drafter
                uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter-template.yml # 3. 릴리즈 노트 설정 파일
                env:
                    GITHUB_TOKEN: ${{ secrets.TOKEN }}
